### ISSUE TITLE
Send Client Certificate in Request

### ISSUE THREAD

**Issue by jonahbron** [vesln/hippie#16]
I figured out how to use a client certificate with Hippie, and I figured I'd post here how it's done.  It's just a matter of using the `use` method to modify the options, like so:

    var hippie = require('hippie');
    var fs = require('fs');
    var path = require('path');

    hippie()
        .use(function (options, next) {
            options.agentOptions = {
                cert: fs.readFileSync(path.resolve(__dirname, 'client.crt')),
                key: fs.readFileSync(path.resolve(__dirname, 'client.key'))
            };
            options.strictSSL = false;
            next(options);
        })
        // ...

**Comment by jonahbron** [comment]
Question: would you like me to submit a pull-request to add this example to the README?

**Comment by vesln** [comment]
that'd be sweet! would love to merge in
