### ISSUE TITLE
supporting basePath

### ISSUE THREAD

**Issue by gdelafosse** [vesln/hippie#27]
I'm using hippie-swagger to test my REST server.
I specified in my swagger file a basePath set to "/api/v1" and one path called "/users".
The following test doesn't work because hippie implementation doesn't interpret the swagger basePath:

    it('works when server refuse content-type', function (done) {
        hippie(app, swagger, options)
            .post('/api/v1/users')
            .send(JSON.parse(fs.readFileSync('user.json')))
            .expectStatus(201)
            .end(function (err, res, body) {
                if (err)  throw err;
                done();
            })
    });

I tried to set a base path with the hippie#base() method but this method required to know the address of the server, which is a dynamic value...

Do you agree that it's a missing feature?
(I can propose a pull request.)

**Comment by vesln** [comment]
at this point, hippie is completely unaware of swagger. we eventually may merge the projects, but until then, i think this issues should be taken to https://github.com/CacheControl/hippie-swagger not hippie

//cc @CacheControl

**Comment by gdelafosse** [comment]
You are right, tihs must be fixed in  https://github.com/CacheControl/hippie-swagger.
Thanks
