### ISSUE TITLE
expectStatus() is not working with end() callback

### ISSUE THREAD

**Issue by dooman87** [vesln/hippie#33]
I have a simple test that checks that endpoint is returning 500 status in the response:

```
	it('should respond with 500 status', function(done) {
		hippie(server)
			.json()
			.get('/endpoint/12345')
			.expectStatus(500)
			.end(function(err, res, body) {
				done();
			});
	});
```

We are doing refactoring to migrate to promises, so new test looks like this:

```
	it('should respond with 500 status', function() {
		return hippie(server)
			.json()
			.get('/endpoint/12345')
			.expectStatus(500)
			.end();
	});
```

Surprisingly, first test is green, however, second is failing. We got 404 statusCode in response. Looks like expectStatus() was ignored for some reason in the first test.

Hippie version is 0.5.0

**Comment by CacheControl** [comment]
@dooman87 looks like the original code is missing some error handling.  if you handle the err, you'll see the spec fail:

```js
it('should respond with 500 status', function(done) {
        hippie(server)
            .json()
            .get('/endpoint/12345')
            .expectStatus(500)
            .end(function(err, res, body) {
                if(err) return done(err);
                done();
            });
    });
```

If this turns out to not be the culprit, feel free to respond and we'll do a deep dive.

**Comment by dooman87** [comment]
@CacheControl Yeah, in that case it will fail for sure. But I was talking about expectStatus(500) which is not failing in case when it should (actual status code is 404 when expected is 500), I suppose.
