### ISSUE TITLE
Please bump the release tag

### ISSUE THREAD

**Issue by rob4629** [vesln/hippie#51]
Hi @morfie78, would you be able to bump the release tag (maybe _0.6.0_??) so that we can use the latest Hippie version in any project that has it as a dependency. I tried, but I don't have permission.

Currently still at _0.5.2_, which doesn't contain the latest changes made in #46 

Thanks

**Comment by morfie78** [comment]
Done! https://www.npmjs.com/package/hippie
Thank you for your contributions.

**Comment by rob4629** [comment]
No problem! I've been given some scope at work to help contribute to O/S libraries.

If you have some work you'd like done, but don't have time to get to, let me know and I'll try to get to it :slightly_smiling_face:
