### ISSUE TITLE
i can't post a file

### ISSUE THREAD

**Issue by ManRueda** [vesln/hippie#9]
Hi @vesln,

I'm trying to post a file to an API, i know you use the request module of @mikeal and he use the form-data module of @felixge. So i think is possible to post a file, but i can't get to the right config.

you've done in the past?

Thanks in advance

**Comment by psstoev** [comment]
Hi @ManRueda,

You can post a file using a middleware to modify the request options, like this:

```js
hippie()
.use(function(options, next) {
  options.formData = {
    your_filename: fs.createReadStream('/your_file')
  };
  next(options);
});
```
More `formData` options [here](https://github.com/request/request#multipartform-data-multipart-form-uploads)
